### ISSUE TITLE
Add support for AdRoll events and conversion value

### ISSUE THREAD

**Issue by jpetey75** [segment-boneyard/analytics.js-integrations#27]
Events: 
`analytics.track('event name');`
becomes
`__adroll.record_user(adroll_segment: 'event name');`

Event properties will include `order_id` and `revenue`:
`analytics.track('event name', {order_id: '12345', revenue: 50});` 

When translated to AdRoll it will become:

``` javascript
__adroll.record_user(adroll_segment: 'event name');
adroll_conversion_value_in_dollars = 50;
adroll_custom_data = {"ORDER_ID": "12345", "USER_ID":"98765"};
```

**Comment by mmahalwy** [comment]
@DirtyAnalytics any luck with the example??

**Comment by jpetey75** [comment]
@mmahalwy I'm not sure about this and I'm sure it's changed since I left that comment, but could you email friends@segment.com with what you're hoping to accomplish? They will be able to get you the example `track` code and update docs if needed :100:
