### ISSUE TITLE
handling dates

### ISSUE THREAD

**Issue by yields** [segment-boneyard/analytics.js-integrations#30]
in most integrations we use `convert-date` which is great except that it doesn't handle `strings`, `numbers` etc...

fix all of those so analytics.js users can safely use `s`, `ms`, `strings` or `Date`.

**Comment by cthorner** [comment]
So the convert-date functionality is converting all my id fields that have a 4 digit number to an invalid Date object. E.g.,

It turns the integer into the year:

Before:
 id: 1087

After:
 id: Fri Dec 31 1086 16:00:00 GMT-0800 (PST)
__proto__: Invalid Date

Should I open a new issue for this?

**Comment by yields** [comment]
@cthorner that sounds really bad, can you open an issue for it? with some more information like integrations that you are using and possibly a way to reproduce, will be helpful in tracking and fixing the issue! :)
